export const CBTI_MIGRATION_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS cbti_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('baseline', 'active', 'paused', 'safety_paused', 'completed', 'maintenance', 'exited')),
    track TEXT NOT NULL DEFAULT 'none' CHECK (track IN ('full', 'gentle', 'none')),
    track_reason TEXT,
    start_date DATE NOT NULL,
    wake_anchor TEXT NOT NULL,
    pending_wake_anchor TEXT,
    wake_anchor_changed_on DATE,
    pending_track TEXT CHECK (pending_track IS NULL OR pending_track IN ('full', 'gentle')),
    prescribed_tib_min INT,
    baseline_tib_min INT,
    baseline_tst_min INT,
    baseline_se DOUBLE PRECISION,
    baseline_bed_time TEXT,
    safety_flags TEXT[] NOT NULL DEFAULT '{}',
    devices_json JSONB NOT NULL DEFAULT '[]',
    intake_json JSONB NOT NULL DEFAULT '{}',
    isi_baseline INT,
    isi_final INT,
    ess_baseline INT,
    paused_at TIMESTAMPTZ,
    paused_from_status TEXT,
    paused_days_total INT NOT NULL DEFAULT 0,
    rebaseline_until DATE,
    active_since_day INT,
    exit_reason TEXT,
    exited_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    consent_version TEXT NOT NULL,
    engine_version TEXT NOT NULL,
    mode_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_cbti_plans_user_live
   ON cbti_plans (user_id) WHERE status <> 'exited'`,
  `CREATE INDEX IF NOT EXISTS idx_cbti_plans_user_created ON cbti_plans (user_id, created_at DESC)`,

  `CREATE TABLE IF NOT EXISTS cbti_consents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES cbti_plans(id) ON DELETE SET NULL,
    consent_version TEXT NOT NULL,
    items_json JSONB NOT NULL,
    archive_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
    device_info_json JSONB NOT NULL DEFAULT '{}',
    withdrawn_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_cbti_consents_user ON cbti_consents (user_id, created_at DESC)`,

  `CREATE TABLE IF NOT EXISTS cbti_diary_entries (
    plan_id UUID NOT NULL REFERENCES cbti_plans(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    night_date DATE NOT NULL,
    bed_time TEXT,
    wake_time TEXT,
    pre_lights_min INT,
    sol_min INT,
    waso_min INT,
    ema_min INT,
    leave_count INT,
    input_mode_json JSONB NOT NULL DEFAULT '{}',
    nap_min INT,
    caffeine BOOLEAN,
    alcohol BOOLEAN,
    sleepiness SMALLINT CHECK (sleepiness IS NULL OR sleepiness BETWEEN 0 AND 4),
    special TEXT CHECK (special IS NULL OR special IN ('sick', 'travel', 'alcohol', 'childcare', 'other')),
    device_tier TEXT,
    device_estimates_json JSONB,
    edit_history_json JSONB NOT NULL DEFAULT '[]',
    client_updated_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (plan_id, night_date)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_cbti_diary_user_night ON cbti_diary_entries (user_id, night_date DESC)`,

  `CREATE TABLE IF NOT EXISTS cbti_night_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID NOT NULL REFERENCES cbti_plans(id) ON DELETE CASCADE,
    event_id TEXT NOT NULL,
    night_date DATE NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('leave_bed', 'return_bed', 'prompt_silent', 'prompt_sound', 'prompt_feedback', 'night_chat', 'device_check', 'app_foreground')),
    occurred_at TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('button', 'device', 'server', 'app')),
    device_sn TEXT,
    confidence DOUBLE PRECISION,
    payload_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, event_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_cbti_night_events_plan_night ON cbti_night_events (plan_id, night_date, occurred_at)`,

  `CREATE TABLE IF NOT EXISTS cbti_settlements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL REFERENCES cbti_plans(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('initial', 'weekly', 'gentle_review')),
    plan_day INT NOT NULL,
    night_date DATE NOT NULL,
    reason TEXT NOT NULL,
    old_tib_min INT,
    new_tib_min INT,
    earliest_bed_time TEXT,
    stats_json JSONB NOT NULL DEFAULT '{}',
    client_result_json JSONB,
    server_result_json JSONB NOT NULL,
    mismatch BOOLEAN NOT NULL DEFAULT FALSE,
    engine_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (plan_id, plan_day)
  )`,

  `CREATE TABLE IF NOT EXISTS cbti_questionnaires (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID NOT NULL REFERENCES cbti_plans(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('isi', 'ess')),
    phase TEXT NOT NULL CHECK (phase IN ('baseline', 'final')),
    answers INT[] NOT NULL,
    score INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (plan_id, kind, phase)
  )`,

  `CREATE TABLE IF NOT EXISTS cbti_night_summaries (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES cbti_plans(id) ON DELETE SET NULL,
    night_date DATE NOT NULL,
    device_id TEXT NOT NULL,
    device_kind TEXT NOT NULL,
    tier TEXT NOT NULL,
    summary_json JSONB NOT NULL DEFAULT '{}',
    baseline_json JSONB,
    retain_until DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, night_date, device_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_cbti_night_summaries_retain ON cbti_night_summaries (retain_until)`,

  `CREATE TABLE IF NOT EXISTS cbti_flags (
    key TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS radar_realtime_series (
    mac TEXT NOT NULL,
    radar_number INT NOT NULL DEFAULT 0,
    bucket_at TIMESTAMPTZ NOT NULL,
    samples INT NOT NULL DEFAULT 0,
    in_bed_samples INT NOT NULL DEFAULT 0,
    unknown_samples INT NOT NULL DEFAULT 0,
    hr_n INT NOT NULL DEFAULT 0,
    hr_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
    hr_sq DOUBLE PRECISION NOT NULL DEFAULT 0,
    rr_n INT NOT NULL DEFAULT 0,
    rr_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
    rr_sq DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (mac, radar_number, bucket_at)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_radar_series_bucket ON radar_realtime_series (bucket_at)`,

  `ALTER TABLE cbti_plans ADD COLUMN IF NOT EXISTS night_profile_json JSONB NOT NULL DEFAULT '{}'`,

  `ALTER TABLE push_devices ADD COLUMN IF NOT EXISTS provider TEXT`,
  `ALTER TABLE push_devices ADD COLUMN IF NOT EXISTS vendor TEXT`,
  `ALTER TABLE push_devices ADD COLUMN IF NOT EXISTS os_version TEXT`,
  `ALTER TABLE push_devices ADD COLUMN IF NOT EXISTS app_version TEXT`,
  `ALTER TABLE push_devices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'general'`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS event_id TEXT`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS attempts INT NOT NULL DEFAULT 0`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending'`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS delivered_ms INT`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS provider TEXT`,
  `ALTER TABLE push_queue ADD COLUMN IF NOT EXISTS vendor TEXT`,
  `UPDATE push_queue SET status = CASE WHEN error IS NULL THEN 'sent' ELSE 'failed' END
   WHERE sent_at IS NOT NULL AND status = 'pending'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_push_queue_user_event
   ON push_queue (user_id, event_id) WHERE event_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_push_queue_status_next ON push_queue (status, next_attempt_at, created_at)`,
  // 专家咨询提交时记下计划状态与当前窗口，供专家端查看（PRD 8.19.2）
  `ALTER TABLE expert_consultations ADD COLUMN IF NOT EXISTS cbti_context JSONB`,
];
