#!/usr/bin/env bash
# 在 GitHub Actions 中运行：从当前 shell 环境变量渲染 .env（secrets 由 workflow 注入）
set -euo pipefail

required=(DATABASE_URL JWT_SECRET)
for k in "${required[@]}"; do
  if [[ -z "${!k:-}" ]]; then
    echo "missing required env: $k" >&2
    exit 1
  fi
done

cat <<EOF
NODE_ENV=${NODE_ENV:-production}
PORT=${PORT:-8787}
DATABASE_URL=${DATABASE_URL}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-30d}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
DEEPSEEK_API_URL=${DEEPSEEK_API_URL:-https://api.deepseek.com/v1/chat/completions}
DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY:-}
SENTRY_DSN=${SENTRY_DSN:-}
RADAR_PUSH_SECRET=${RADAR_PUSH_SECRET:-}
WECHAT_APP_ID=${WECHAT_APP_ID:-}
WECHAT_APP_SECRET=${WECHAT_APP_SECRET:-}
TENCENT_SMS_SECRET_ID=${TENCENT_SMS_SECRET_ID:-}
TENCENT_SMS_SECRET_KEY=${TENCENT_SMS_SECRET_KEY:-}
TENCENT_SMS_SDK_APP_ID=${TENCENT_SMS_SDK_APP_ID:-}
TENCENT_SMS_SIGN_NAME=${TENCENT_SMS_SIGN_NAME:-}
TENCENT_SMS_TEMPLATE_ID=${TENCENT_SMS_TEMPLATE_ID:-}
TENCENT_SMS_REGION=${TENCENT_SMS_REGION:-ap-guangzhou}
SMS_MOCK=${SMS_MOCK:-}
SMS_MOCK_CODE=${SMS_MOCK_CODE:-123456}
SMS_CODE_TTL_SEC=${SMS_CODE_TTL_SEC:-300}
SMS_SEND_INTERVAL_SEC=${SMS_SEND_INTERVAL_SEC:-60}
SMS_DAILY_LIMIT_PER_PHONE=${SMS_DAILY_LIMIT_PER_PHONE:-10}
SMS_HOURLY_LIMIT_PER_IP=${SMS_HOURLY_LIMIT_PER_IP:-20}
SMS_MAX_VERIFY_ATTEMPTS=${SMS_MAX_VERIFY_ATTEMPTS:-5}
QUOTA_GUEST_CHAT=${QUOTA_GUEST_CHAT:-15}
QUOTA_GUEST_INTERPRET=${QUOTA_GUEST_INTERPRET:-2}
QUOTA_USER_CHAT=${QUOTA_USER_CHAT:-80}
QUOTA_USER_INTERPRET=${QUOTA_USER_INTERPRET:-10}
FCM_SERVER_KEY=${FCM_SERVER_KEY:-}
FCM_PROJECT_ID=${FCM_PROJECT_ID:-}
WORKER_POLL_INTERVAL_MS=${WORKER_POLL_INTERVAL_MS:-5000}
EOF
